# Generated by Django 5.2.16 on 2026-07-18 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('igdb_genre_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('igdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('critic_rating', models.FloatField(blank=True, null=True)),
                ('community_rating', models.FloatField(blank=True, null=True)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('cached_at', models.DateTimeField()),
                ('genres', models.ManyToManyField(related_name='games', to='games.genre')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('want_to_play', 'Want to Play'), ('playing', 'Playing'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], max_length=20)),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='library_entries', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('critic_rating__isnull', True), models.Q(('critic_rating__gte', 0), ('critic_rating__lte', 100)), _connector='OR'), name='critic_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('community_rating__isnull', True), models.Q(('community_rating__gte', 0), ('community_rating__lte', 100)), _connector='OR'), name='community_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='libraryentry',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_user_game'),
        ),
        migrations.AddConstraint(
            model_name='libraryentry',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 1), ('score__lte', 10)), _connector='OR'), name='score_range'),
        ),
        migrations.AddConstraint(
            model_name='libraryentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['completed', 'abandoned']), _negated=True), ('score__isnull', False), _connector='OR'), name='score_required_when_finished'),
        ),
    ]
