# Generated by Django 5.2.16 on 2026-07-19 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='libraryentry',
            constraint=models.CheckConstraint(condition=models.Q(('review__isnull', True), ('review__length__lte', 8000), _connector='OR'), name='review_max_length', violation_error_message='Review must not exceed 8000 characters.'),
        ),
    ]
